### ISSUE TITLE
[Bug]: Music bug in the entire application

### ISSUE THREAD

**Issue by ayush-t02** [ChromeGaming/Dot-Box#614] opened 2024-07-25 04:22 UTC
### Give a brief about the bug ✍️

Sound on / off is redundant, when you navigate from home to any other page and come back to home page 2 separate music files are being played. when you click on sound off it stops one of them but the other keeps playing

### What is the expected behavior? 🤔

one page should be associated with only one sound track and tracks should not leak into other pages

### Provide step by step information reproduce the bug 📄

navigate from home to any other page and back to home

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MastanSayyad** [comment] 2024-07-25 05:36
It is happening due to two things:
- When we redirect to other page it opens in new tab (home page remain active with its music) and that page's music starts to play leading to redundant sound
- In game interface the sound toggle is not working, the music keeps playing even after clicking on it!

**Comment by ayush-t02** [comment] 2024-07-25 06:30
do you want me to assign this issue to you?

**Comment by MastanSayyad** [comment] 2024-07-25 08:19
Yes, assign it!  @ayush-t02

**Comment by ayush-t02** [comment] 2024-07-25 13:50
@MastanSayyad music state is still the same on my end alongwith the home screen misaligned

**Comment by MastanSayyad** [comment] 2024-07-25 13:54
> @MastanSayyad music state is still the same on my end alongwith the home screen misaligned

Home screen was misaligned due to PR #619 
in index.html I have only made changes in lets go link

**Comment by MastanSayyad** [comment] 2024-07-25 13:56
@ayush-t02 Yes I can see it didnt worked out, on my side it was working fine , I have added error handling in console so I will just check whats the issue, and fix it

**Comment by MastanSayyad** [comment] 2024-07-25 14:00
one thing i noticed is that the sound is a little faint as compared to the original sound so it might be a problem with the server loading the bg.mp3 @ayush-t02 

![image](https://github.com/user-attachments/assets/042c2ce8-951b-408d-a0a0-a6c7e9a15fe1)

Error handling console displayed this error, So I will try to fix it! as the code is woking fine the only issue is loading the background music

**Comment by ayush-t02** [comment] 2024-07-25 14:51
yup correct

**Comment by ayush-t02** [comment] 2024-07-25 14:52
I reopened the issue to avoid extra work

**Comment by MastanSayyad** [comment] 2024-07-25 14:57
Yeah, good idea, if someone have better solution they can also try it!

**Comment by MastanSayyad** [comment] 2024-07-28 13:27
@ayush-t02 The issue is solved now so, I will close the issue!

**Comment by ayush-t02** [comment] 2024-07-29 08:43
was this issue fixed by you?

**Comment by ayush-t02** [comment] 2024-07-29 08:44
and it still doesn't seem solved on my end

**Closed** 2024-07-29 08:44 UTC
Labels: gssoc
